
pool:
  vmImage: ubuntu-16.04

steps:

  - bash: |
      (cd XPlat/Mono.Posix && make)
    displayName: Run the build

  - task: PublishBuildArtifacts@1
    displayName: Publish the packages
    inputs:
      artifactName: nuget
      pathToPublish: XPlat/Mono.Posix/build

  - bash: |
      (cd XPlat/Mono.Posix && make test)
    displayName: Run the tests

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: XPlat/Mono.Posix/Test/TestResult*.xml
